<?php
/**
 * @file
 * Contact: hansdotcom@gmail.com.
 */

/**
 * Implementation of hook_permission().
 */
function responsive_image_mapping_permission() {
  return array(
    'administer responsive image mappings' => array(
      'title' => t('Administer responsive image mappings'),
      'description' => t('Allow image presets to be mapped responsively to another preset.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function responsive_image_mapping_menu() {
  $items['admin/config/responsiveimages/mappings'] = array(
    'title' => 'Responsive images - Current mappings',
    'description' => 'Configure responsive images and their current mappings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('responsive_image_mapping_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'responsive_image_mapping.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 *
 * We can use this to define new styles
 * function hook_image_default_styles()
 *
 */